### PR TITLE
mgr key capability support

### PR DESCRIPTION
**Pull request by nrdmn**
This adds support for manager key capability introduced in version 11 (kraken).

### CODE REVIEW

**Comment by spjmurray** [comment]
Hey @nrdmn thanks for this.  I wasn't planning on officially supporting kraken as it's not an LTS release (and more work :wink:).  If you could try the [luminous beta branch](https://github.com/spjmurray/puppet-ceph/tree/12.2.x) this may just work for you.  I've done some initial sniff tests and kraken passes acceptance testing at least without having to mess with keys.

**Comment by nrdmn** [comment]
Hi @spjmurray, I hadn't seen the beta branch when I opened this pull request.
'ceph pg stat' won't work unless my client.admin key has mgr caps.

**Comment by spjmurray** [comment]
Okay, I'd prefer it if we could keep this stuff in the Luminous branch so people don't try to start using it on things it isn't advertised to work with :smile: If you could give that a try and see if it works that would be excellent.  If so can you re-raise the pull request targeting that branch?  Also revert the versioning change, that's my job ;p

**Comment by nrdmn** [comment]
Okay, I'll do :smile:

**Pull request closed without merging**
